### ISSUE TITLE
ЧО ДЕЛАИТИ?

### ISSUE THREAD

**Issue by Razenpok** [RWB01/First-Prototype#25]
ММММ?

**Comment by tennobyte** [comment]
Сидим тута, фуфлыжно сидим

**Comment by Razenpok** [comment]
И ФСЁ?

**Comment by RWB01** [comment]
Ага, гавнецо коммитим. Мержим потихоньку.
В выходные запустими на проде сайтец.

**Comment by Razenpok** [comment]
А чё эт вообще? Магисрака?

**Comment by RWB01** [comment]
Агась, она самая.

**Comment by RWB01** [comment]
Ты эт. Уже курва, или пока еще нет?

**Comment by Razenpok** [comment]
Ещё не пшек

**Comment by Razenpok** [comment]
На днях начну оформлять визу

**Comment by Razenpok** [comment]
Снесёте этот issue? У меня нет прав.

**Comment by RWB01** [comment]
А чо? Нехуевый чатик

**Comment by Razenpok** [comment]
Ага, с эмодзями

**Comment by Razenpok** [comment]
Жаль, стикеры не завезли

**Comment by Razenpok** [comment]
Алсо

**Comment by Razenpok** [comment]
![image](https://user-images.githubusercontent.com/8434406/32836744-e840b1ce-ca1b-11e7-90de-8ec23cd3bd18.png)
Порядок версий, алло?

**Comment by RWB01** [comment]
Ну да. Это я обосрался. посмотрел в git tag какой самый последний и сделал инкремент

**Comment by RWB01** [comment]
ДА ВОТ ТОЛЬКО ТАМ КОЕ-ЧТО ПОИНТЕРЕСНЕЙ

**Comment by RWB01** [comment]
v1.10.0
v1.10.1
v1.4.0
v1.5.0
v1.6.0
v1.7.0
v1.7.1
v1.8.0
v1.8.1
v1.9.0
v1.9.1
v1.9.2
v1.9.3
v1.9.4
v1.9.5
v1.9.6
v1.9.7
v1.9.8

**Comment by RWB01** [comment]
ОПАНЬКИ

**Comment by RWB01** [comment]
По хорошему надо впилить либо грант, либо каку-нибудь другую хуйню для этого

**Comment by Razenpok** [comment]
Wat

**Comment by Razenpok** [comment]
А, лолблять

**Comment by RWB01** [comment]
Ага

**Comment by RWB01** [comment]
Бро, я спатки. До завтра.

**Comment by Razenpok** [comment]
Чмоки
